name: my_app
description: "Groundwater HEI & HPI Index Calculator"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_map: ^7.0.2   # latest stable version (as of 2025)
  latlong2: ^0.9.1
  # Core Flutter packages
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.16

  # File handling (CSV, Excel, PDF)
  file_picker: ^8.0.6
  csv: ^6.0.0
  excel: ^4.0.2
  syncfusion_flutter_pdf: ^27.1.50

  # Local database
  sqflite: ^2.3.3

  # State management
  provider: ^6.1.2

  # Networking
  http: ^1.2.2
  connectivity_plus: ^6.1.0

  # Maps & location
  google_maps_flutter: ^2.6.0
  geolocator: ^12.0.0

  # Key-value storage
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Optional assets
  # assets:
  #   - assets/sample.csv
  #   - assets/sample.xlsx
  #   - assets/sample.pdf
